fix: an unexpected 'equal_nan' keyword argument (#66)
* fix: TypeError: _unique_dispatcher() got an unexpected keyword argument 'equal_nan'

'equal_nan' was introduced from Numpy 1.24
https://numpy.org/doc/1.24/reference/generated/numpy.unique.html

* minimum installed version has to be the minimum tested version

---------

Co-authored-by: Jim Pivarski <jpivarski@gmail.com>