fix: TypeError: _unique_dispatcher() got an unexpected keyword argument 'equal_nan'
'equal_nan' was introduced from Numpy 1.24
https://numpy.org/doc/1.24/reference/generated/numpy.unique.html